AWSTemplateFormatVersion: '2010-09-09'
Description: WebSocket API for PDF-Talker

Parameters:
  TranscribeProxyLambdaArn:
    Type: String
    Description: The ARN of the pdf-talker-transcribe-proxy Lambda function.

Resources:
  PdfTalkerWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: pdf-talker-voice-socket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - /
        - - "integrations"
          - !Ref ConnectIntegration

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join
        - /
        - - "integrations"
          - !Ref DisconnectIntegration

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Join
        - /
        - - "integrations"
          - !Ref DefaultIntegration

  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TranscribeProxyLambdaArn}/invocations"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TranscribeProxyLambdaArn}/invocations"

  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TranscribeProxyLambdaArn}/invocations"

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - DefaultRoute

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref PdfTalkerWebSocketApi
      StageName: prod
      DeploymentId: !Ref Deployment
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TranscribeProxyLambdaArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PdfTalkerWebSocketApi}/*/*"

Outputs:
  WebSocketURL:
    Description: "WebSocket URL"
    Value: !Sub "wss://${PdfTalkerWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/prod"